version: '3'

services:
  backend:
    container_name: 'kupipodariday-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-compose-kupipodariday
    restart: always
    env_file: .env
    ports:
      - '4000:3000'
    depends_on:
      - database
    networks:
      - my_network
      - internal-network
    
  database:
    container_name: 'postgres'
    image: postgres:alpine
    env_file: .env
    restart: always
    ports:
      - '5432:5432'
    networks:
      - internal-network
    volumes:
      - postgres_data_dir:/data/postgres
    
  frontend:
    container_name: 'kupipodariday-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-compose-kupipodariday
    restart: always
    ports:
      - '8081:80'
    networks:
      - my_network

volumes:
  postgres_data_dir:

networks:
  internal-network:
    driver: bridge
    internal: true
  my_network:
    driver: bridge